import { createSlice, isAnyOf, type PayloadAction } from "@reduxjs/toolkit";
import { type ITodo, type ITodoSlice } from "./todoType";
import { todoAddThunk, removeTodoThunk } from "./todoThunk";

type UpdateTodoPayload = Partial<Omit<ITodo, "id">> & { id: string };

const initialState: ITodoSlice = {
  todos: [],
  state: "stale",
};

// export const todoAction = createAction<ITodo>("todoSlice/addTodo");

// console.log(
//   "Todo action is: ",
//   todoAction({
//     id: "123",
//     title: "Title hai ye",
//     status: "completed",
//   }),
// );

// "CreateSlice" is a function that is use to create a "slice".
// Here we initialize "slice" with "initialState", "reducers", "extraReducers" (for asyncThunk),
const todoSlice = createSlice({
  name: "todoSlice",
  initialState,
  /* A reducer is a pure function, which means it should only calculate and return the next state.
     We should not perform side effects like API calls or async operations inside the reducer.
     
     It takes two arguments:
        1. current state
        2. Action:
            i. type (slice_name/reducer_function_name)
            ii. Actual Payload data.

    * It returns an action object like:
        {
          type: "slice_name/reducer_function_name",
          payload: data
        }

    * Let's see what happened, If I call reducer function.
        i. increase(); // Generate message with type and payload,
        ii. dispatch(message); // Sends message to redux
        iii. Reducer store // Find correct reducer and update the states
  */
  reducers: {
    addTodo(state, action: PayloadAction<ITodo>) {
      // "state": Current state data (Proxy array)
      // "action": It's an object which has {"type": "name/function_name -> (todoSlice/addTodo)", payload:""}
      // We need to return "new state" or "update existing one"

      return {
        ...state,
        todos: [...state.todos, action.payload],
      };
    },
    removeTodo(state, action) {
      const todos = state.todos.filter((t) => t.id !== action.payload);

      return {
        ...state,
        todos,
      };
    },
    // "PayloadAction" is a generic type used to tell the type of "payload"
    updateTodo(state, action: PayloadAction<UpdateTodoPayload>) {
      const updatedTodos = state.todos.map((t) =>
        t.id === action.payload.id ? { ...t, ...action.payload } : t,
      );

      return {
        ...state,
        todos: updatedTodos,
      };
    },
    toggleTodo(state, action: PayloadAction<string>) {
      return {
        ...state,
        todos: state.todos.map((t) =>
          t.id == action.payload
            ? {
                ...t,
                status: t.status === "completed" ? "pending" : "completed",
              }
            : t,
        ),
      };
    },
  },
  extraReducers: (builder) => {
    /*
     * Builder is used to handle "asyncThunk", It have few options to match the current state of "thunk" based on it we can perform some tasks.
     * Let's see some important one:
     *    i. addCase: Used to matcher only task at a time and a function for handling state
     *    ii. addMatcher: Use to match multiple "cases" at a time using some utility functions like "isAnyOf (It's like || operator)", "isAllOf (It's like && operator)", "isPending, isFulfilled"
     */

    builder.addCase(todoAddThunk.fulfilled, (state, action) => {
      return {
        ...state,
        todos: [...state.todos, action.payload],
      };
    });

    builder.addCase(removeTodoThunk.fulfilled, (state, action) => {
      return {
        ...state,
        todos: state.todos.filter((t) => t.id !== action.payload),
      };
    });

    builder.addMatcher(
      isAnyOf(todoAddThunk.pending, removeTodoThunk.pending),
      (state) => {
        state.state = "loading";
      },
    );

    builder.addMatcher(
      isAnyOf(todoAddThunk.fulfilled, removeTodoThunk.fulfilled),
      (state) => {
        state.state = "stale";
      },
    );
  },
});

/*
- These are not reducers. They are action creators generated by "Redux Toolkit" using `createAction`.
- Action Object passed to reducer function to update the state and return new state.

When called, they return an action object containing:
- type
- payload
*/
export const { addTodo, removeTodo, updateTodo, toggleTodo } =
  todoSlice.actions;
export default todoSlice.reducer;
